// Generated by tools/build-sw.mjs — do not edit by hand.
// Precache-on-install, cache-first. Ported from BARE METAL's tools/sw.
const CACHE = "netplus-9ce3bf991b654042";
const SHELL = "./";
const PRECACHE = [
  "./",
  "css/style.css",
  "data/course-u1.js",
  "data/course-u2.js",
  "data/course-u3.js",
  "data/course-u4.js",
  "data/course-u5.js",
  "data/d1-concepts.js",
  "data/d2-implementation.js",
  "data/d3-operations.js",
  "data/d4-security.js",
  "data/d5-troubleshooting.js",
  "data/pbqs.js",
  "fonts/OFL.txt",
  "fonts/ibm-plex-mono-400.woff2",
  "fonts/ibm-plex-mono-500.woff2",
  "fonts/ibm-plex-mono-600.woff2",
  "fonts/ibm-plex-sans-400.woff2",
  "fonts/ibm-plex-sans-500.woff2",
  "fonts/ibm-plex-sans-600.woff2",
  "fonts/ibm-plex-sans-700.woff2",
  "icons/apple-touch-icon.png",
  "icons/icon-192.png",
  "icons/icon-512.png",
  "js/app.js",
  "js/course.js",
  "js/exam.js",
  "js/pbq.js",
  "js/pwa.js",
  "js/results.js",
  "js/scoring.js",
  "js/sync.js",
  "js/theme.js",
  "js/tutor.js",
  "manifest.webmanifest"
];

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE)
      .then((cache) => cache.addAll(PRECACHE))
      // skipWaiting: a freshly installed version takes over without waiting for
      // every old tab to close — the simplest update model for a one-person app.
      .then(() => self.skipWaiting()),
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(
        keys.filter((k) => k !== CACHE).map((k) => caches.delete(k)),
      ))
      .then(() => self.clients.claim()),
  );
});

// ignoreVary matters: crossorigin-attributed loads send an Origin header whose
// Vary would otherwise fail to match the precached response. Everything cached
// here is a same-origin static asset keyed by URL alone.
const MATCH = { ignoreSearch: true, ignoreVary: true };

self.addEventListener("fetch", (event) => {
  const req = event.request;
  if (req.method !== "GET") return;
  // Cross-origin is never intercepted. The sync API and Turnstile must always
  // reach the network so sync.js can report its own offline state.
  if (new URL(req.url).origin !== self.location.origin) return;
  event.respondWith(
    caches.match(req, MATCH).then((hit) => {
      if (hit) return hit;
      // Any navigation is the app shell; serve it so offline launch works.
      if (req.mode === "navigate") {
        return caches.match(SHELL, MATCH).then((shell) => shell || fetch(req));
      }
      return fetch(req);
    }),
  );
});
