// Generates sw.js — the precache service worker. Port of BARE METAL's
// tools/sw/generate.ts, adapted for a repo with no build step.
//
// Run after changing ANY app file:  node tools/build-sw.mjs
// test/sw-fresh.test.mjs fails if the committed sw.js is out of date, which is
// what stands in for the freshness Metal gets free from `npm run build`.

import { readdirSync, readFileSync, writeFileSync, statSync } from "node:fs";
import { createHash } from "node:crypto";
import { join, dirname } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");

// An allowlist, not a blocklist: docs/, test/, tools/, .claude/ and anything
// added later can never leak into the precache by accident. sw.js itself sits
// at root and is structurally incapable of precaching itself.
const DIRS = ["css", "js", "data", "fonts", "icons"];
const ROOT_FILES = ["index.html", "manifest.webmanifest"];
const CACHE_PREFIX = "netplus";

export function collect(root = ROOT) {
  const out = [...ROOT_FILES];
  for (const dir of DIRS) out.push(...walk(root, dir));
  return out.sort();
}

function walk(root, rel) {
  const out = [];
  for (const name of readdirSync(join(root, rel))) {
    const child = `${rel}/${name}`;
    if (statSync(join(root, child)).isDirectory()) out.push(...walk(root, child));
    else out.push(child);
  }
  return out;
}

// Text files are hashed with CRLF normalised to LF. Git's core.autocrlf (on by
// default on Windows) rewrites line endings in the working tree on clone,
// checkout, branch switch and restore. Hashing raw bytes would then move the
// version hash without one byte of real content changing, so the freshness test
// would fail on a clean tree — and a guard that cries wolf gets ignored, which
// is exactly how a genuinely stale sw.js ships. Binaries are hashed as-is.
const TEXT = /\.(html|css|js|mjs|json|webmanifest|txt|svg)$/;

export function build(root = ROOT) {
  const files = collect(root);
  const hash = createHash("sha256");
  for (const f of files) {
    const buf = readFileSync(join(root, f));
    hash
      .update(f)
      .update("\0")
      .update(TEXT.test(f) ? buf.toString("utf8").replace(/\r\n/g, "\n") : buf);
  }
  const version = hash.digest("hex").slice(0, 16);
  // "./" is the app shell: that is what a navigation to the directory actually
  // requests, and index.html is never fetched by that name.
  const urls = ["./", ...files.filter((f) => f !== "index.html")];
  return { version, urls, source: render(version, urls) };
}

function render(version, urls) {
  return `// Generated by tools/build-sw.mjs — do not edit by hand.
// Precache-on-install, cache-first. Ported from BARE METAL's tools/sw.
const CACHE = "${CACHE_PREFIX}-${version}";
const SHELL = "./";
const PRECACHE = ${JSON.stringify(urls, null, 2)};
// CacheStorage is ORIGIN-scoped, not scope-scoped. Three PWAs share
// https://mofchris.github.io, so an unfiltered sweep here deletes the other
// apps' precaches — and they do not repopulate until their own sw.js changes
// bytes, permanently breaking their offline launch. Only ever delete our own.
const OWNED = /^${CACHE_PREFIX}-/;

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE)
      .then((cache) => cache.addAll(PRECACHE))
      // skipWaiting: a freshly installed version takes over without waiting for
      // every old tab to close — the simplest update model for a one-person app.
      .then(() => self.skipWaiting()),
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(
        keys.filter((k) => OWNED.test(k) && k !== CACHE).map((k) => caches.delete(k)),
      ))
      .then(() => self.clients.claim()),
  );
});

// ignoreVary matters: crossorigin-attributed loads send an Origin header whose
// Vary would otherwise fail to match the precached response. Everything cached
// here is a same-origin static asset keyed by URL alone.
const MATCH = { cacheName: CACHE, ignoreSearch: true, ignoreVary: true };

self.addEventListener("fetch", (event) => {
  const req = event.request;
  if (req.method !== "GET") return;
  // Cross-origin is never intercepted. The sync API and Turnstile must always
  // reach the network so sync.js can report its own offline state.
  if (new URL(req.url).origin !== self.location.origin) return;
  event.respondWith(
    caches.match(req, MATCH).then((hit) => {
      if (hit) return hit;
      // Any navigation is the app shell; serve it so offline launch works.
      if (req.mode === "navigate") {
        return caches.match(SHELL, MATCH).then((shell) => shell || fetch(req));
      }
      return fetch(req);
    }),
  );
});
`;
}

// Only write when run directly, so importing this from a test has no side effect.
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const { version, urls, source } = build();
  writeFileSync(join(ROOT, "sw.js"), source);
  console.log(`sw.js: ${urls.length} URLs precached, cache ${CACHE_PREFIX}-${version}`);
}
